/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_POSTIT;

import java.awt.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author dlastwishes
 */
public class Main_Program extends javax.swing.JFrame {

    Login_Program loginPanel = new Login_Program();
    Process process = new Process();
    

    long userId = loginPanel.userId;
    String username = process.checkUsername(userId);
    int top = 5;
    static String res = "";
    /**
     * Creates new form Main_Program
     */
    public Main_Program() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setSize(780,450);
        setLabel();
        showEvent();
        
    }
    public void alert() throws ClassNotFoundException, SQLException{
        try{
            SimpleDateFormat df= new SimpleDateFormat("dd/MM/yyyy");
         String date= process.checkDate();
         Connection conn = Connectionbuilder.connect();
         String sql = "select * from APP.postit where userid = "+userId+"";
         Statement std = conn.createStatement();
         std.executeQuery(sql);
         ResultSet rs = std.getResultSet();
         int check=0 , i =0;
         String alertMsg = "";
          alertMsg += "This is your event(s) for today.\n\n";
         while(rs.next()){
             System.out.println(df.format(rs.getDate("date"))+" "+date);
              if(df.format(rs.getDate("date")).equalsIgnoreCase(date)){
                  i++;
                  this.countNoti.setText(String.valueOf(i));
           alertMsg += i+". "+rs.getString("postname")+"\nInfo :"+rs.getString("postinfo");
           alertMsg += "\n------------------------------------\n";
           check=1;
        }
        }
         
         if(check==0){
             JOptionPane.showMessageDialog(null,"No event for today");
         }
         else if(check == 1){
             JOptionPane.showMessageDialog(null, alertMsg);
         }
          conn.close();
        }
        catch(Exception ex){
            ex.printStackTrace();
            System.exit(0);
        }
        
       
    }
    
    public void showEvent() throws ClassNotFoundException, SQLException {
        String result = "";
        SimpleDateFormat dateFormat = new SimpleDateFormat("yy/MM/yyyy");
        String thisDate = String.valueOf(dateFormat.getCalendar().getTime());
        this.showEventText.setEditable(false);
//        long userId = 104;
        

        ArrayList<PostEvent> results = Process.execute("select * from APP.postit where userid =" + userId + "");
        if (results != null) {
            result += "Hello " + username + " this is your list of Post IT\n\n";
            result += "Current Time is " + thisDate + "\n\n";
            for (int j = top; j >= 1; j--) {
                for (int i = 0; i < results.size(); i++) {
                    if (results.get(i).getImportant() == j | String.valueOf(results.get(i).getDate()) == thisDate) {
                        result += results.get(i);
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "You don't have any event. Please,Add your event.");
        }

        this.showEventText.setText(result);
        
    }

    private void setLabel() throws ClassNotFoundException, SQLException {
 long userid = loginPanel.userId;
        Process checkusername = new Process();
        String username = checkusername.checkUsername(userid);
        this.HeadLabel.setText("Welcome " + username + " to POST IT");
        if (process.chechStatus(userId)) {
            this.modeLabel.setIcon(new ImageIcon(getClass().getResource("/GUI_POSTIT/admin_mini.png")));
        } else {
             this.modeLabel.setIcon(new ImageIcon(getClass().getResource("/GUI_POSTIT/user_mini.png")));
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        showEventText = new javax.swing.JTextArea();
        modeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HeadLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        countNoti = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Index : POST IT");
        getContentPane().setLayout(null);

        showEventText.setColumns(20);
        showEventText.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        showEventText.setLineWrap(true);
        showEventText.setRows(5);
        showEventText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(showEventText);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(170, 60, 580, 320);

        modeLabel.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        modeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(modeLabel);
        modeLabel.setBounds(50, 10, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/mini_res.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 10, 50, 50);

        HeadLabel.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        HeadLabel.setText("Welcome to POST IT");
        getContentPane().add(HeadLabel);
        HeadLabel.setBounds(170, 10, 408, 43);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/newNote_mini.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 60, 60);

        countNoti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countNoti.setText("0");
        getContentPane().add(countNoti);
        countNoti.setBounds(650, 10, 40, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/edit_mini.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 150, 60, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/search_min.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 60, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/logout_mini.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 10, 40, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/exit_mini.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 320, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/refresh_mini.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 60, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/save_mini.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 240, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_POSTIT/efjiemgrgre.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -110, 770, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeLabelMouseClicked
        try {
            // TODO add your handling code here:
            if (process.chechStatus(userId)) {
                Admin_Menu admin = new Admin_Menu();
                admin.setVisible(true);
                admin.setLocationRelativeTo(null);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modeLabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            // TODO add your handling code here:
            alert();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         Add_Event add_panel = new Add_Event();
        add_panel.setVisible(true);
        add_panel.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
          Search_Program search_Panel = new Search_Program();
        search_Panel.setVisible(true);
        search_Panel.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        try {
           Edit_Program edit = new Edit_Program();
           edit.setVisible(true);
           edit.setLocationRelativeTo(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main_Program.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          Print_Program print = new Print_Program();
        print.setVisible(true);
        print.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        try{
            showEvent();
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        Login_Program loginPanel = new Login_Program();
        loginPanel.setVisible(true);
        loginPanel.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main_Program().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JLabel countNoti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JTextArea showEventText;
    // End of variables declaration//GEN-END:variables
}
